# Generated by Django 2.2.1 on 2019-06-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('fullname', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('famale', '女')], default='male', max_length=10, verbose_name='性别')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='邮箱')),
                ('title', models.IntegerField()),
                ('department', models.IntegerField()),
                ('descrabe', models.CharField(max_length=500, verbose_name='个人介绍')),
                ('reg_data', models.DateTimeField(verbose_name='注册日期')),
            ],
        ),
    ]
