# Generated by Django 2.2.1 on 2019-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190603_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(on_delete=False, to='user.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.ForeignKey(on_delete=False, to='user.Title', verbose_name='职位'),
        ),
    ]
